# ################################
# Model: Speaker Verification Baseline
# Authors: Hwidong Na 2020
#          Mirco Ravanelli 2020
# ################################

seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Folders and train_log file
data_folder: /mnt/datadrive/datasets/spkveri/mrt1/spk450/wav/ #e.g., /localscratch/voxceleb1
output_folder: /mnt/results/speechbrain/spkr_rec/results/silverbullet-testenv/test-01-benchmarks
save_folder: /mnt/results/speechbrain/spkr_rec/results/silverbullet-testenv/test-01-benchmarks/save
device: 'cuda:0'
#voxceleb_source: /mnt/datadrive/datasets/voxceleb/voxceleb1

# Use the following links for the official voxceleb splits:
# VoxCeleb1 (cleaned): https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test2.txt
# VoxCeleb1-H (cleaned): https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/list_test_hard2.txt
# VoxCeleb1-E (cleaned): https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/list_test_all2.txt.
# VoxCeleb1-E and VoxCeleb1-H lists are drawn from the VoxCeleb1 training set.
# Therefore you cannot use any files in VoxCeleb1 for training if you are using these lists for testing.
verification_file: /mnt/training/silverbullet-testenv/test-01-benchmarks/save/veri_test.txt

# Here, the pretrained embedding model trained with train_speaker_embeddings.py hparams/train_ecapa_tdnn.yaml
# is downloaded from the speechbrain HuggingFace repository.
# However, a local path pointing to a directory containing your checkpoints may also be specified
# instead (see pretrainer below)
pretrain_path: speechbrain/spkrec-ecapa-voxceleb

# csv files
train_data: !ref /mnt/training/silverbullet-testenv/test-01-benchmarks/save/train.csv
enrol_data: !ref /mnt/training/silverbullet-testenv/test-01-benchmarks/save/enrol.csv
test_data: !ref /mnt/training/silverbullet-testenv/test-01-benchmarks/save/test.csv

batch_size: 1 #8
score_norm: s-norm  # z-norm t-norm s-norm (uncomment to enable it)
cohort_size:  1130 # amount of imposter utterances in normalization cohort # og:20000
n_train_snts: 400000 # used for normalization stats

# Feature parameters
n_mels: 80
# left_frames: 0
# right_frames: 0
# deltas: False

# Dataloader options
train_dataloader_opts:
    batch_size: !ref <batch_size>

enrol_dataloader_opts:
    batch_size: !ref <batch_size>

test_dataloader_opts:
    batch_size: !ref <batch_size>

compute_features: !new:speechbrain.lobes.features.Fbank
    n_mels: !ref <n_mels>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: sentence
    std_norm: False

embedding_model: !new:speechbrain.lobes.models.ECAPA_TDNN.ECAPA_TDNN
    input_size: !ref <n_mels>
    channels: [1024, 1024, 1024, 1024, 3072]
    kernel_sizes: [5, 3, 3, 3, 1]
    dilations: [1, 2, 3, 4, 1]
    attention_channels: 128
    lin_neurons: 192

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <save_folder>
    loadables:
        embedding_model: !ref <embedding_model>
    paths:
        embedding_model: !ref <pretrain_path>/embedding_model.ckpt
